version: '3'

services:
  meetaroo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
  redirector:
    image: nginx:alpine
    volumes:
     - ./redirector.nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "8080:80"
