version: '3'

services:
  db:
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: x1Y6Dfb4ElF7C6JbEo170raDSaQRcb71
      POSTGRES_USER: meetaroo
      POSTGRES_DB: meetaroo
    volumes:
     - ./data:/var/lib/postgresql/data
  migrator:
    image: migrator
    build:
      context: ./Migrator
      dockerfile: Dockerfile
    environment:
      - SLEEP=5
      - DATABASE_HOST=db
    volumes:
      - ./migrations:/srv/migrations
    depends_on:
      - "db"
  meetaroo:
    image: meetaroo
    build:
      context: ./Meetaroo
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=db
    volumes:
      - ./migrations:/srv/migrations
      - /usr/local/share/findecks:/usr/local/share/findecks
    depends_on:
      - "db"