version: '3'

services:
  meetaroo:
    image: meetaroo
    build:
      context: ./Meetaroo
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=db
  db:
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: x1Y6Dfb4ElF7C6JbEo170raDSaQRcb71
      POSTGRES_USER: meetaroo
      POSTGRES_DB: meetaroo