version: '3'

services:
  meetaroo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    ports:
      - "80:80"
  db:
    volumes:
      - /dev/sda1/data:/var/lib/postgresql/data
  redirector:
    image: nginx:alpine
    volumes:
     - ./redirector.nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "8080:80"
