version: '3'

services:
  meetaroo:
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
    volumes:
     - ./Meetaroo/wwwroot:/app/wwwroot
  ssl_terminator:
    image: nginx:alpine
    volumes:
     - ./ssl_dev/ssl_termination_proxy.conf:/etc/nginx/nginx.conf:ro
     - ./ssl_dev/cert:/usr/local/share/findecks
    ports:
     - "443:443"
    depends_on:
     - "meetaroo"
  db:
    ports:
     - "5432:5432"
  # pgAdmin README:
  # 1. In your browser go to http://localhost:65325/
  # 2. Log in with the credentials below
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "65325:80"
    environment:
     - PGADMIN_DEFAULT_EMAIL=dev@findecks.com
     - PGADMIN_DEFAULT_PASSWORD=meetaroo
    volumes:
     - ./pgadmin/pgadmin4.db:/var/lib/pgadmin/pgadmin4.db