#!/usr/bin/env sh

# Create migration
# Run as create_migration <migration set> <name>
# Example: create_migration shared add_users

cat << EOF > "../migrations/$1/$(date -u +%y%m%d%H%M%S)_$2.sql"
START TRANSACTION;

-- Migration here

COMMIT;
EOF
