#!/bin/sh

# First parameter is passed to docker-compose, so you can use "run_dev -d" to run in background

(
    cd ..
    set -e

    # Let's assume we have dotnet on development machine
    dotnet restore ./Meetaroo.no_docker.sln && dotnet publish ./Meetaroo.no_docker.sln -c Debug -o ./obj/Docker/publish
    docker-compose -f docker-compose.yml -f docker-compose.development-overrides.yml up --build $1
)
